require('core.plugins')
require('core.mappings')
require('core.colors')
require('core.config')

require('plugins.neotree')
require('plugins.treesitter')
require('plugins.lsp')
require('plugins.cmp')
require('plugins.mason')
require('plugins.telescope')
require('plugins.null-ls')
